

setup_dirs:
	cargo new hello --lib


build:
	cargo build-bpf


setupsdk:
	curl -sSfL https://release.solana.com/v1.10.19/install | sh

setup_tssdk:
	npm install -g ts-node
	npm install --save @solana/web3.js
	npm install --save @solana/spl-token
	npm install --save @solana/wallet-adapter-wallets @solana/wallet-adapter-base
	


